### ISSUE TITLE
Permission error: custom_dict_word.txt

### ISSUE THREAD

**Issue by trieunus** [Querela/thai-segmenter#4]
`    tokens = tokenize(text)
  File "/home/pai/lib/python3.6/site-packages/thai_segmenter/tasks.py", line 86, in tokenize
    segmenter = _get_segmenter_default(segmenter)
  File "/home/pai/lib/python3.6/site-packages/thai_segmenter/tasks.py", line 71, in _get_segmenter_default
    __segmenter = get_segmenter()
  File "/home/pai/lib/python3.6/site-packages/thai_segmenter/tasks.py", line 56, in get_segmenter
    segmenter = thai_segmenter.sentence_segmenter.sentence_segmenter()
  File "/home/pai/lib/python3.6/site-packages/thai_segmenter/sentence_segmenter.py", line 27, in __init__
    self.set_custom_dict(custom_dict)
  File "/home/pai/lib/python3.6/site-packages/thai_segmenter/sentence_segmenter.py", line 51, in set_custom_dict
    with codecs.open(filename, "w", encoding="utf-8") as f:
  File "/home/pai/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/home/pai/lib/python3.6/site-packages/thai_segmenter/tools/custom_dict_word.txt'`

**Comment by ZJaume** [comment]
This tool is basically unusable on any static container or environment with read-only filesystem. Setting the custom dict to none avoids that write
```
s = sentence_segmenter(custom_dict=None)
```
but it still tries to copy a file then loading the word processing module, which does not have any sense.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/thai_segmenter/sentence_segmenter.py", line 31, in __init__
    self.wp = wp.word_processing(self.dict_name, sentence_segmenter.filename_orchid)
  File "/usr/local/lib/python3.10/dist-packages/thai_segmenter/word_processing.py", line 25, in __init__
    shutil.copyfile(os.path.join(self.dict_dir, dict_file_paragraph), dict_file)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.10/dist-packages/thai_segmenter/tools/lexitron.txt'
```
